// This file needs to be generated by something like gen_api_typings.py

// Wrapper for calling "native" code as async functions
function callAsyncAPI(args) {
    return new Promise(res => {
        FormItInterface.CallMethodDirect(args, (json) => res(JSON.parse(json)));
    });
}

// This is example "generated" output
if (!window.FormIt) {
    window.FormIt = {};
    window.FormIt.GroupEdit = {};
    window.FormIt.GroupEdit.GetEditingHistoryID = function() {
        args = {
            TestAPI:"FormIt.GroupEdit.GetEditingHistoryID"
        };
        return callAsyncAPI(args);
    };
}

if (!window.WSM) {
    window.WSM = {};
    window.WSM.APICreateBlock = function(nHistoryID, point3d1, point3d2) {
        args = {
            TestAPI: "WSM.APICreateBlock",
            nHistoryID: nHistoryID,
            point3d1: point3d1,
            point3d2: point3d2
        };
        return callAsyncAPI(args);
    };
    window.WSM.Geom = {};
    window.WSM.Geom.Point3d = function(x,y,z) {
        args = {
            TestAPI: "WSM.Geom.Point3d",
            x: x,
            y: y,
            z: z
        };
        return callAsyncAPI(args);
    };
}
